framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict

        # FORCE le préfixe de l'URL générée (Solution à ton problème)
        public_prefix: /assets/

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
